name: Build & Deploy Unity WebGL

# Fire pipeline on merge to main.

on:
  workflow_dispatch:

# env:
#   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#   UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
#   UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  
jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - uses: actions/checkout@v2
        name: Checkout repository
        with:
          lfs: true
    
      # Cache
      - uses: actions/cache@v2
        name: Cache
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # unityVersion: 2020.3.15f2
      # - uses: game-ci/unity-test-runner@v3
      #   env:
      #     UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      #   with:
      #     projectPath: path/to/your/project
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          # projectPath: EventDrivenCharacterController

      # Output 
      - uses: actions/upload-artifact@v2
        name: Upload
        with:
          name: Build
          path: build
      # - name: Zip build
      #   run: |
      #     pushd build/StandaloneWindows64
      #     zip -r ../../StandaloneWindows64.zip .
      #     popd

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: StandaloneWindows64.zip
      #     name: Release ${{ github.ref }}
